// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqlgen.proto

package sqlgen

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PK int32

const (
	PK_NONE PK = 0
	PK_AUTO PK = 1
	PK_MAN  PK = 2
)

var PK_name = map[int32]string{
	0: "NONE",
	1: "AUTO",
	2: "MAN",
}

var PK_value = map[string]int32{
	"NONE": 0,
	"AUTO": 1,
	"MAN":  2,
}

func (x PK) Enum() *PK {
	p := new(PK)
	*p = x
	return p
}

func (x PK) String() string {
	return proto.EnumName(PK_name, int32(x))
}

func (x *PK) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PK_value, data, "PK")
	if err != nil {
		return err
	}
	*x = PK(value)
	return nil
}

func (PK) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9cff16fc493290, []int{0}
}

type OPERATION int32

const (
	OPERATION_C OPERATION = 0
	OPERATION_R OPERATION = 1
	OPERATION_U OPERATION = 2
	OPERATION_D OPERATION = 3
)

var OPERATION_name = map[int32]string{
	0: "C",
	1: "R",
	2: "U",
	3: "D",
}

var OPERATION_value = map[string]int32{
	"C": 0,
	"R": 1,
	"U": 2,
	"D": 3,
}

func (x OPERATION) Enum() *OPERATION {
	p := new(OPERATION)
	*p = x
	return p
}

func (x OPERATION) String() string {
	return proto.EnumName(OPERATION_name, int32(x))
}

func (x *OPERATION) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OPERATION_value, data, "OPERATION")
	if err != nil {
		return err
	}
	*x = OPERATION(value)
	return nil
}

func (OPERATION) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9cff16fc493290, []int{1}
}

type Table struct {
	Name                 *string     `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Crud                 []OPERATION `protobuf:"varint,2,rep,name=crud,enum=sqlgen.OPERATION" json:"crud,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9cff16fc493290, []int{0}
}
func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Table) GetCrud() []OPERATION {
	if m != nil {
		return m.Crud
	}
	return nil
}

var E_Sqlgen = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         800200,
	Name:          "sqlgen.sqlgen",
	Tag:           "varint,800200,opt,name=sqlgen",
	Filename:      "sqlgen.proto",
}

var E_StoreName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800201,
	Name:          "sqlgen.StoreName",
	Tag:           "bytes,800201,opt,name=StoreName",
	Filename:      "sqlgen.proto",
}

var E_Table = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Table)(nil),
	Field:         800100,
	Name:          "sqlgen.table",
	Tag:           "bytes,800100,opt,name=table",
	Filename:      "sqlgen.proto",
}

var E_Jsonb = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         800101,
	Name:          "sqlgen.jsonb",
	Tag:           "varint,800101,opt,name=jsonb",
	Filename:      "sqlgen.proto",
}

var E_Dbcol = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800110,
	Name:          "sqlgen.dbcol",
	Tag:           "bytes,800110,opt,name=dbcol",
	Filename:      "sqlgen.proto",
}

var E_Dbpk = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*PK)(nil),
	Field:         800111,
	Name:          "sqlgen.dbpk",
	Tag:           "varint,800111,opt,name=dbpk,enum=sqlgen.PK",
	Filename:      "sqlgen.proto",
}

var E_Dbfk = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800112,
	Name:          "sqlgen.dbfk",
	Tag:           "bytes,800112,opt,name=dbfk",
	Filename:      "sqlgen.proto",
}

func init() {
	proto.RegisterEnum("sqlgen.PK", PK_name, PK_value)
	proto.RegisterEnum("sqlgen.OPERATION", OPERATION_name, OPERATION_value)
	proto.RegisterType((*Table)(nil), "sqlgen.Table")
	proto.RegisterExtension(E_Sqlgen)
	proto.RegisterExtension(E_StoreName)
	proto.RegisterExtension(E_Table)
	proto.RegisterExtension(E_Jsonb)
	proto.RegisterExtension(E_Dbcol)
	proto.RegisterExtension(E_Dbpk)
	proto.RegisterExtension(E_Dbfk)
}

func init() { proto.RegisterFile("sqlgen.proto", fileDescriptor_2a9cff16fc493290) }

var fileDescriptor_2a9cff16fc493290 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xe3, 0x40,
	0x18, 0x86, 0x9b, 0x34, 0xd9, 0x6d, 0xbe, 0xdd, 0x2d, 0xd9, 0x39, 0x15, 0x51, 0x8c, 0x82, 0x58,
	0x7a, 0x48, 0xa5, 0xa2, 0xc2, 0x20, 0x48, 0xab, 0x2d, 0x48, 0x69, 0x52, 0xc6, 0xf6, 0xe2, 0xad,
	0x69, 0xa6, 0xa1, 0x1a, 0x33, 0x31, 0x49, 0xff, 0xa3, 0xfe, 0x0f, 0xbd, 0x54, 0x50, 0x7f, 0x82,
	0xcc, 0x4c, 0x52, 0x0f, 0x8a, 0x3d, 0x7d, 0x93, 0xcc, 0xfb, 0x7c, 0xf3, 0xf0, 0xc2, 0xdf, 0xf4,
	0x3e, 0x0c, 0x68, 0x64, 0xc7, 0x09, 0xcb, 0x18, 0xfa, 0x25, 0xbf, 0x36, 0xac, 0x80, 0xb1, 0x20,
	0xa4, 0x4d, 0xf1, 0xd7, 0x5b, 0xcc, 0x9a, 0x3e, 0x4d, 0xa7, 0xc9, 0x3c, 0xce, 0x58, 0x22, 0x93,
	0xbb, 0x1d, 0xd0, 0x47, 0x13, 0x2f, 0xa4, 0x08, 0x81, 0x16, 0x4d, 0xee, 0x68, 0x4d, 0xb1, 0xd4,
	0xba, 0x41, 0xc4, 0x19, 0xed, 0x81, 0x36, 0x4d, 0x16, 0x7e, 0x4d, 0xb5, 0xca, 0xf5, 0x6a, 0xeb,
	0xbf, 0x9d, 0xbf, 0xe1, 0x0e, 0xbb, 0xa4, 0x3d, 0xba, 0x74, 0x1d, 0x22, 0xae, 0x1b, 0x3b, 0xa0,
	0x0e, 0xfb, 0xa8, 0x02, 0x9a, 0xe3, 0x3a, 0x5d, 0xb3, 0xc4, 0x4f, 0xed, 0xf1, 0xc8, 0x35, 0x15,
	0xf4, 0x1b, 0xca, 0x83, 0xb6, 0x63, 0xaa, 0x8d, 0x7d, 0x30, 0x56, 0x14, 0xd2, 0x41, 0x39, 0x37,
	0x4b, 0x7c, 0x10, 0x53, 0xe1, 0x63, 0x6c, 0xaa, 0x7c, 0x5c, 0x98, 0x65, 0x7c, 0x0c, 0xb9, 0x3b,
	0xda, 0xb4, 0xa5, 0xbc, 0x5d, 0xc8, 0xdb, 0xbd, 0x79, 0x48, 0xdd, 0x38, 0x9b, 0xb3, 0x28, 0xad,
	0x3d, 0xbc, 0x1c, 0x58, 0x4a, 0xbd, 0x42, 0xf2, 0x34, 0x3e, 0x05, 0xe3, 0x2a, 0x63, 0x09, 0x75,
	0xb8, 0xf7, 0xcf, 0xe8, 0xa3, 0x40, 0x0d, 0xf2, 0x09, 0xe0, 0x1e, 0xe8, 0x99, 0x68, 0x61, 0xfb,
	0x0b, 0x39, 0xa0, 0x69, 0x3a, 0x09, 0x56, 0xf0, 0xd3, 0x92, 0xc3, 0x7f, 0x5a, 0xff, 0x8a, 0x32,
	0x44, 0x7b, 0x44, 0xe2, 0xf8, 0x04, 0xf4, 0x9b, 0x94, 0x45, 0xde, 0xfa, 0x3d, 0xcf, 0x4b, 0xe9,
	0x2f, 0xf3, 0xf8, 0x08, 0x74, 0xdf, 0x9b, 0xb2, 0x10, 0x6d, 0x7d, 0xa3, 0x4e, 0x43, 0xbf, 0xc0,
	0x5e, 0x97, 0xd2, 0x5d, 0xa6, 0xf1, 0x19, 0x68, 0xbe, 0x17, 0xdf, 0xae, 0xa3, 0xde, 0x04, 0x55,
	0x6d, 0x41, 0x21, 0x3d, 0xec, 0x13, 0x01, 0xe2, 0x43, 0xbe, 0x60, 0xb6, 0x76, 0xc1, 0x7b, 0xfe,
	0xac, 0x08, 0x77, 0x2a, 0xd7, 0x79, 0xeb, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x12, 0x4d,
	0x1f, 0x76, 0x02, 0x00, 0x00,
}
