// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqlgen/sqlgen.proto

// import "github.com/gogo/protobuf/protobuf/google/protobuf/descriptor.proto";

package sqlgen

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PK int32

const (
	PK_NONE PK = 0
	PK_AUTO PK = 1
	PK_MAN  PK = 2
)

var PK_name = map[int32]string{
	0: "NONE",
	1: "AUTO",
	2: "MAN",
}

var PK_value = map[string]int32{
	"NONE": 0,
	"AUTO": 1,
	"MAN":  2,
}

func (x PK) Enum() *PK {
	p := new(PK)
	*p = x
	return p
}

func (x PK) String() string {
	return proto.EnumName(PK_name, int32(x))
}

func (x *PK) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PK_value, data, "PK")
	if err != nil {
		return err
	}
	*x = PK(value)
	return nil
}

func (PK) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ada5781a4e9b1a15, []int{0}
}

type OPERATION int32

const (
	OPERATION_C OPERATION = 0
	OPERATION_R OPERATION = 1
	OPERATION_U OPERATION = 2
	OPERATION_D OPERATION = 3
)

var OPERATION_name = map[int32]string{
	0: "C",
	1: "R",
	2: "U",
	3: "D",
}

var OPERATION_value = map[string]int32{
	"C": 0,
	"R": 1,
	"U": 2,
	"D": 3,
}

func (x OPERATION) Enum() *OPERATION {
	p := new(OPERATION)
	*p = x
	return p
}

func (x OPERATION) String() string {
	return proto.EnumName(OPERATION_name, int32(x))
}

func (x *OPERATION) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OPERATION_value, data, "OPERATION")
	if err != nil {
		return err
	}
	*x = OPERATION(value)
	return nil
}

func (OPERATION) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ada5781a4e9b1a15, []int{1}
}

type Table struct {
	Name                 *string     `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Crud                 []OPERATION `protobuf:"varint,2,rep,name=crud,enum=sqlgen.OPERATION" json:"crud,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_ada5781a4e9b1a15, []int{0}
}
func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Table) GetCrud() []OPERATION {
	if m != nil {
		return m.Crud
	}
	return nil
}

var E_Sqlgen = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         800200,
	Name:          "sqlgen.sqlgen",
	Tag:           "varint,800200,opt,name=sqlgen",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_StoreName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800201,
	Name:          "sqlgen.StoreName",
	Tag:           "bytes,800201,opt,name=StoreName",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Table = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Table)(nil),
	Field:         800100,
	Name:          "sqlgen.table",
	Tag:           "bytes,800100,opt,name=table",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Jsonb = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         800101,
	Name:          "sqlgen.jsonb",
	Tag:           "varint,800101,opt,name=jsonb",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Dbcol = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800110,
	Name:          "sqlgen.dbcol",
	Tag:           "bytes,800110,opt,name=dbcol",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Dbpk = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*PK)(nil),
	Field:         800111,
	Name:          "sqlgen.dbpk",
	Tag:           "varint,800111,opt,name=dbpk,enum=sqlgen.PK",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Dbfk = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800112,
	Name:          "sqlgen.dbfk",
	Tag:           "bytes,800112,opt,name=dbfk",
	Filename:      "sqlgen/sqlgen.proto",
}

func init() {
	proto.RegisterEnum("sqlgen.PK", PK_name, PK_value)
	proto.RegisterEnum("sqlgen.OPERATION", OPERATION_name, OPERATION_value)
	proto.RegisterType((*Table)(nil), "sqlgen.Table")
	proto.RegisterExtension(E_Sqlgen)
	proto.RegisterExtension(E_StoreName)
	proto.RegisterExtension(E_Table)
	proto.RegisterExtension(E_Jsonb)
	proto.RegisterExtension(E_Dbcol)
	proto.RegisterExtension(E_Dbpk)
	proto.RegisterExtension(E_Dbfk)
}

func init() { proto.RegisterFile("sqlgen/sqlgen.proto", fileDescriptor_ada5781a4e9b1a15) }

var fileDescriptor_ada5781a4e9b1a15 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xd1, 0x4e, 0xe2, 0x40,
	0x14, 0x86, 0x69, 0x69, 0x77, 0xe9, 0xd9, 0x2c, 0xe9, 0xce, 0xde, 0x10, 0xa3, 0x11, 0x4d, 0x8c,
	0x84, 0x8b, 0x62, 0x30, 0x6a, 0xd2, 0x98, 0x18, 0x50, 0x48, 0x0c, 0xa1, 0x25, 0x23, 0x3c, 0x00,
	0x6d, 0x87, 0x5a, 0x2d, 0x9d, 0xda, 0x96, 0x77, 0xd4, 0xf7, 0xd0, 0x1b, 0x4c, 0xd4, 0x47, 0x30,
	0x33, 0xd3, 0xc2, 0x85, 0x46, 0xae, 0xce, 0x99, 0x9c, 0xf3, 0xfd, 0xfd, 0x7a, 0xe0, 0x7f, 0xfa,
	0x10, 0xfa, 0x24, 0x6a, 0x89, 0x62, 0xc4, 0x09, 0xcd, 0x28, 0xfa, 0x25, 0x5e, 0x5b, 0x5d, 0x3f,
	0xc8, 0x6e, 0x17, 0x8e, 0xe1, 0xd2, 0x79, 0xcb, 0xa7, 0x3e, 0x6d, 0xf1, 0xb1, 0xb3, 0x98, 0xad,
	0x1b, 0x9f, 0x52, 0x3f, 0x24, 0xeb, 0xb7, 0x47, 0x52, 0x37, 0x09, 0xe2, 0x8c, 0x26, 0x22, 0x6b,
	0xbf, 0x0b, 0xea, 0x78, 0xea, 0x84, 0x04, 0x21, 0x50, 0xa2, 0xe9, 0x9c, 0xd4, 0xa4, 0xba, 0xdc,
	0xd0, 0x30, 0xef, 0xd1, 0x01, 0x28, 0x6e, 0xb2, 0xf0, 0x6a, 0x72, 0xbd, 0xdc, 0xa8, 0xb6, 0xff,
	0x19, 0xb9, 0x85, 0x3d, 0xea, 0xe1, 0xce, 0xf8, 0xda, 0xb6, 0x30, 0x1f, 0x37, 0xf7, 0x40, 0x1e,
	0x0d, 0x50, 0x05, 0x14, 0xcb, 0xb6, 0x7a, 0x7a, 0x89, 0x75, 0x9d, 0xc9, 0xd8, 0xd6, 0x25, 0xf4,
	0x1b, 0xca, 0xc3, 0x8e, 0xa5, 0xcb, 0xcd, 0x43, 0xd0, 0x56, 0x14, 0x52, 0x41, 0xba, 0xd4, 0x4b,
	0xac, 0x60, 0x5d, 0x62, 0x65, 0xa2, 0xcb, 0xac, 0x5c, 0xe9, 0x65, 0xf3, 0x14, 0xf2, 0xbf, 0x43,
	0xdb, 0x86, 0x90, 0x37, 0x0a, 0x79, 0xa3, 0x1f, 0x84, 0xc4, 0x8e, 0xb3, 0x80, 0x46, 0x69, 0xed,
	0xf1, 0xf5, 0xa8, 0x2e, 0x35, 0x2a, 0x38, 0xdf, 0x36, 0xcf, 0x41, 0xbb, 0xc9, 0x68, 0x42, 0x2c,
	0xe6, 0xfd, 0x33, 0xfa, 0xc4, 0x51, 0x0d, 0xaf, 0x01, 0xb3, 0x0f, 0x6a, 0xc6, 0xaf, 0xb0, 0xfb,
	0x85, 0x1c, 0x92, 0x34, 0x9d, 0xfa, 0x2b, 0xf8, 0x79, 0xc9, 0xe0, 0x3f, 0xed, 0xbf, 0xc5, 0x31,
	0xf8, 0xf5, 0xb0, 0xc0, 0xcd, 0x33, 0x50, 0xef, 0x52, 0x1a, 0x39, 0x9b, 0x73, 0x5e, 0x96, 0xc2,
	0x5f, 0xec, 0x9b, 0x27, 0xa0, 0x7a, 0x8e, 0x4b, 0x43, 0xb4, 0xf3, 0x8d, 0x3a, 0x09, 0xbd, 0x02,
	0x7b, 0x5b, 0x0a, 0x77, 0xb1, 0x6d, 0x5e, 0x80, 0xe2, 0x39, 0xf1, 0xfd, 0x26, 0xea, 0x9d, 0x53,
	0xd5, 0x36, 0x14, 0xd2, 0xa3, 0x01, 0xe6, 0xa0, 0x79, 0xcc, 0x02, 0x66, 0x1b, 0x03, 0x3e, 0xf2,
	0xcf, 0xf2, 0xe5, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x97, 0xdd, 0x32, 0x95, 0x02, 0x00,
	0x00,
}
