// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sqlgen/sqlgen.proto

// import "github.com/gogo/protobuf/protobuf/google/protobuf/descriptor.proto";

package sqlgen

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PK int32

const (
	PK_NONE PK = 0
	PK_AUTO PK = 1
	PK_MAN  PK = 2
)

var PK_name = map[int32]string{
	0: "NONE",
	1: "AUTO",
	2: "MAN",
}

var PK_value = map[string]int32{
	"NONE": 0,
	"AUTO": 1,
	"MAN":  2,
}

func (x PK) Enum() *PK {
	p := new(PK)
	*p = x
	return p
}

func (x PK) String() string {
	return proto.EnumName(PK_name, int32(x))
}

func (x *PK) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PK_value, data, "PK")
	if err != nil {
		return err
	}
	*x = PK(value)
	return nil
}

func (PK) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ada5781a4e9b1a15, []int{0}
}

var E_Sqlgen = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         800200,
	Name:          "sqlgen.sqlgen",
	Tag:           "varint,800200,opt,name=sqlgen",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_StoreName = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800201,
	Name:          "sqlgen.StoreName",
	Tag:           "bytes,800201,opt,name=StoreName",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Dbtable = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800100,
	Name:          "sqlgen.dbtable",
	Tag:           "bytes,800100,opt,name=dbtable",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Dbselect = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         800101,
	Name:          "sqlgen.dbselect",
	Tag:           "varint,800101,opt,name=dbselect",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Dbinsert = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         800102,
	Name:          "sqlgen.dbinsert",
	Tag:           "varint,800102,opt,name=dbinsert",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Dbcol = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800110,
	Name:          "sqlgen.dbcol",
	Tag:           "bytes,800110,opt,name=dbcol",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Dbpk = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*PK)(nil),
	Field:         800111,
	Name:          "sqlgen.dbpk",
	Tag:           "varint,800111,opt,name=dbpk,enum=sqlgen.PK",
	Filename:      "sqlgen/sqlgen.proto",
}

var E_Dbfk = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         800112,
	Name:          "sqlgen.dbfk",
	Tag:           "bytes,800112,opt,name=dbfk",
	Filename:      "sqlgen/sqlgen.proto",
}

func init() {
	proto.RegisterEnum("sqlgen.PK", PK_name, PK_value)
	proto.RegisterExtension(E_Sqlgen)
	proto.RegisterExtension(E_StoreName)
	proto.RegisterExtension(E_Dbtable)
	proto.RegisterExtension(E_Dbselect)
	proto.RegisterExtension(E_Dbinsert)
	proto.RegisterExtension(E_Dbcol)
	proto.RegisterExtension(E_Dbpk)
	proto.RegisterExtension(E_Dbfk)
}

func init() { proto.RegisterFile("sqlgen/sqlgen.proto", fileDescriptor_ada5781a4e9b1a15) }

var fileDescriptor_ada5781a4e9b1a15 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd1, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0x07, 0x70, 0x37, 0xa7, 0xeb, 0xbe, 0x83, 0x94, 0x78, 0x11, 0x51, 0x9c, 0x37, 0xf1, 0xd0,
	0x8a, 0xa2, 0x87, 0xa8, 0xc8, 0x0e, 0x7a, 0x19, 0x6b, 0x47, 0xd5, 0x07, 0x68, 0x9a, 0x6f, 0xa5,
	0x18, 0x9b, 0xda, 0xc4, 0x77, 0xd4, 0xf7, 0x50, 0x0f, 0x13, 0xd4, 0x47, 0x90, 0x35, 0xe9, 0x76,
	0x50, 0xe8, 0x4e, 0x6d, 0xc2, 0xff, 0xf7, 0xcf, 0x17, 0x02, 0x9b, 0xea, 0x49, 0xa4, 0x98, 0xfb,
	0xe6, 0xe3, 0x15, 0xa5, 0xd4, 0x92, 0xac, 0x9b, 0xd5, 0x76, 0x3f, 0x95, 0x32, 0x15, 0xe8, 0x57,
	0xbb, 0xec, 0x79, 0xe2, 0x73, 0x54, 0x49, 0x99, 0x15, 0x5a, 0x96, 0x26, 0x79, 0xb8, 0x0f, 0xed,
	0xf1, 0x90, 0x38, 0xd0, 0x09, 0xc2, 0xe0, 0xda, 0x5d, 0x99, 0xfd, 0x0d, 0xee, 0xef, 0x42, 0xb7,
	0x45, 0xba, 0xb0, 0x3a, 0x1a, 0x04, 0x6e, 0x9b, 0x9e, 0x81, 0xad, 0x23, 0x3b, 0x9e, 0xe9, 0xf3,
	0xea, 0x3e, 0xef, 0x26, 0x13, 0x18, 0x16, 0x3a, 0x93, 0xb9, 0xda, 0x7a, 0xf9, 0x3c, 0xea, 0xb7,
	0x0e, 0x9c, 0xc8, 0xa6, 0xe9, 0x05, 0xf4, 0x6e, 0xb5, 0x2c, 0x31, 0x88, 0x1f, 0xb1, 0x81, 0xbe,
	0x56, 0xb4, 0x17, 0x2d, 0x00, 0x3d, 0x87, 0x2e, 0x67, 0x3a, 0x66, 0x02, 0xc9, 0xde, 0x1f, 0x3b,
	0x42, 0xa5, 0xe2, 0x74, 0xce, 0xdf, 0xa6, 0x86, 0xd7, 0x82, 0x5e, 0x82, 0xc3, 0x99, 0x42, 0x81,
	0x89, 0x6e, 0xd6, 0xef, 0x53, 0x33, 0xf7, 0x9c, 0x18, 0x9e, 0xe5, 0x0a, 0xcb, 0x25, 0xf8, 0xc7,
	0x82, 0x1b, 0x42, 0x4f, 0x61, 0x8d, 0xb3, 0x44, 0x0a, 0xb2, 0xfb, 0xcf, 0xa5, 0x51, 0xf0, 0x5a,
	0x7e, 0xd9, 0xb1, 0x4d, 0x9a, 0x5e, 0x41, 0x87, 0xb3, 0xe2, 0xa1, 0x49, 0x7d, 0x57, 0x6a, 0xe3,
	0x18, 0x3c, 0xfb, 0xe4, 0xe3, 0x61, 0x54, 0x41, 0x7a, 0x32, 0x2b, 0x98, 0x34, 0x16, 0xfc, 0xd8,
	0x63, 0xab, 0xf0, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x49, 0xe5, 0x11, 0x40, 0x02, 0x00,
	0x00,
}
