// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test/proto/jsonb/test.proto

package join

import (
	context "context"
	sql "database/sql"
	driver "database/sql/driver"
	json "encoding/json"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	pg "github.com/roderm/protoc-gen-go-sqlmap/lib/pg"
	_ "github.com/roderm/protoc-gen-go-sqlmap/sqlgen"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _ = context.TODO
var _ = pg.NONE
var _ = sql.Open
var _ = driver.IsValue
var _ = json.Valid

type TestStore struct {
	conn *sql.DB
}

func NewTestStore(conn *sql.DB) *TestStore {
	return &TestStore{conn}
}

func (m *Product) Scan(value interface{}) error {
	buff, ok := value.([]byte)
	if !ok {
		return fmt.Errorf("Failed % ", value)
	}
	m.ProductID = string(buff)
	return nil
}

func (m *Product) Value() (driver.Value, error) {
	return m.ProductID, nil
}

type queryProductConfig struct {
	Store        *TestStore
	filter       pg.Where
	beforeReturn []func(map[string]*Product) error
	cb           []func(*Product)
	rows         map[string]*Product
}

type ProductOption func(*queryProductConfig)

func ProductFilter(filter pg.Where) ProductOption {
	return func(config *queryProductConfig) {
		if config.filter == nil {
			config.filter = filter
		} else {
			config.filter = pg.AND(config.filter, filter)
		}
	}
}

func ProductOnRow(cb func(*Product)) ProductOption {
	return func(s *queryProductConfig) {
		s.cb = append(s.cb, cb)
	}
}

func (s *TestStore) Product(ctx context.Context, opts ...ProductOption) (map[string]*Product, error) {
	config := &queryProductConfig{
		Store:  s,
		filter: pg.NONE(),
		rows:   make(map[string]*Product),
	}
	for _, o := range opts {
		o(config)
	}

	err := s.selectProduct(ctx, config.filter, func(row *Product) {
		config.rows[row.ProductID] = row
		for _, cb := range config.cb {
			cb(row)
		}
	})
	if err != nil {
		return config.rows, err
	}

	for _, cb := range config.beforeReturn {
		err = cb(config.rows)
		if err != nil {
			return config.rows, err
		}
	}
	return config.rows, nil
}
func (s *TestStore) selectProduct(ctx context.Context, filter pg.Where, withRow func(*Product)) error {
	where, vals := pg.GetWhereClause(filter)
	stmt, err := s.conn.PrepareContext(ctx, `
	SELECT "product_id", "product_name", "product_config" 
	FROM "tbl_product"
	`+where)
	if err != nil {
		return err
	}
	cursor, err := stmt.QueryContext(ctx, vals...)
	if err != nil {
		return err
	}
	defer cursor.Close()
	for cursor.Next() {
		row := new(Product)
		err := cursor.Scan(&row.ProductID, &row.ProductName, &row.Config)
		if err != nil {
			return err
		}
		withRow(row)
	}
	return nil
}

func (m *ProductConfig) Scan(value interface{}) error {
	buff, ok := value.([]byte)
	if !ok {
		return fmt.Errorf("Failed % ", value)
	}
	return json.Unmarshal(buff, m)
}

func (m *ProductConfig) Value() (driver.Value, error) {
	return json.Marshal(m)
}
