// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lib/proto/timestamptz/timestamptz.proto

package timestamptz

import (
	"database/sql/driver"
	fmt "fmt"
	"time"
)

func (n *TimestampTZ) Value() (driver.Value, error) {
	if n.GetSeconds() == 0 {
		return nil, nil
	}
	loc, err := time.LoadLocation(n.GetZone())
	if err != nil {
		return nil, err
	}
	date, err := time.ParseInLocation("", "", loc)
	if err != nil {
		return date, err
	}
	date.Add(time.Second * time.Duration(n.GetSeconds()))
	date.Add(time.Nanosecond * time.Duration(n.GetNanos()))
	return date, nil
}

func (n *TimestampTZ) Scan(value interface{}) error {
	date, ok := value.(time.Time)
	if !ok {
		return fmt.Errorf("Failed %+v ", value)
	}
	n.Seconds = date.Unix()
	n.Nanos = int32(date.UnixNano())
	n.Zone, _ = date.Zone()
	return nil
}
