name: build
on:
  push:
    branches:
      - master

jobs:
  run:
    name: build
    runs-on: ['ubuntu-latest']
    strategy:
      matrix:
        GOARCH: ["386", "amd64", "arm64"]
        GOOS: ["darwin", "linux", "windows"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -o protoc-gen-go-sql
