name: build
on:
  push:
    branches:
      - master

jobs:
  run:
    name: build
    runs-on: ["ubuntu-latest"]
    strategy:
      matrix:
        GOARCH: ["386", "amd64"]
        GOOS: ["linux", "windows"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - run: make install  
      - run: make test
      - run: go get .
      - run: GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -o protoc-gen-go-sql
