name: test
on:
  push:

jobs:
  run:
    name: build
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - uses: bufbuild/buf-setup-action@v0.6.0
      - run: make install  
      - run: make test
      - run: go get .
